spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://120.78.85.140:3306/jpa
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update #更新或者创建数据表
    show-sql: true #控制台显示SQL